export const planIngAdministrativa = [
  { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3009137", nombre: "Estadística III", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3011166", nombre: "Fundamentos de Sistemas de Información e Inteligencia de Negocios", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000006-M", nombre: "Cálculo de Varias Variables", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006935", nombre: "Procesos Estocásticos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3009297", nombre: "Series de Tiempo Univariadas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3007340", nombre: "Diseño de Experimentos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3010394", nombre: "Teoría Básica de la Probabilidad", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000018-M", nombre: "Física Moderna", creditos: 3, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006852", nombre: "Laboratorio de Física Moderna", creditos: 1, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3009743", nombre: "Microeconomía I", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3009951", nombre: "Macroeconomía I", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010507", nombre: "Contabilidad General y de Costos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010521", nombre: "Administración Financiera", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010512", nombre: "Introducción a las Finanzas Corporativas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010518", nombre: "Matemáticas Financieras", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007324", nombre: "Investigación de Operaciones I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007325", nombre: "Investigación de Operaciones II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3011198", nombre: "Introducción a la Ingeniería Administrativa", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010425", nombre: "Teoría Administrativa y Organizacional", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010411", nombre: "Innovación y Gestión Tecnológica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010500", nombre: "Gestión del Talento Humano", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010410", nombre: "Gestión de Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010403", nombre: "Derecho para la Administración", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010396", nombre: "Administración Estratégica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010524", nombre: "Fundamentos de Mercadeo", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007323", nombre: "Investigación de Mercados", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007331", nombre: "Simulación de Sistemas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007202", nombre: "Fundamentos de Economía", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007210", nombre: "Medición Económica", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007287", nombre: "Econometría", creditos: 2, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007193", nombre: "Economía Matemática", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3009953", nombre: "Microeconomía II", creditos: 4, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007301", nombre: "Macroeconomía II", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007302", nombre: "Macroeconomía III", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007182", nombre: "Comercio Mundial", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010527", nombre: "Introducción a la Estructuración de Derivados", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010525", nombre: "Futuros y Opciones", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010513", nombre: "Inversiones Bajo Riesgo", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010689", nombre: "Mercados Financieros", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007304", nombre: "Teoría de Portafolios", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007305", nombre: "Modelos de Valoración de Empresas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010523", nombre: "Formulación y Evaluación Financiera de Proyectos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007183", nombre: "Desarrollo Económico", creditos: 4, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007288", nombre: "Economía Colombiana", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007331", nombre: "Simulación de Sistemas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007311", nombre: "Dinámica de Sistemas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007872", nombre: "Sistemas Complejos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010415", nombre: "Introducción al Análisis de Decisiones", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3011020", nombre: "Fundamentos de Analítica", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010397", nombre: "Administración Pública", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010499", nombre: "Gerencia de Proyectos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010423", nombre: "Sistemas de Compensación", creditos: 2, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010510", nombre: "Derecho Laboral", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010405", nombre: "Diseño Organizacional", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010404", nombre: "Desarrollo de Habilidades Gerenciales", creditos: 2, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3011067", nombre: "Blockchain y Ambientes Empresariales Descentralizados", creditos: 4, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3011068", nombre: "Metodologías Ágiles para la Gestión de Proyectos", creditos: 4, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3011011", nombre: "Transformación Digital de Entornos Empresariales", creditos: 4, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3007368", nombre: "Comportamiento del Consumidor", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010519", nombre: "Mercadeo Internacional", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3008663", nombre: "Estimulación de la Demanda", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010526", nombre: "Gestión de Distribución", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010522", nombre: "Administración de Ventas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010517", nombre: "Marketing Digital", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010516", nombre: "Marca", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" },
  { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" }
];

export default planIngAdministrativa;
