export const planIngAdministrativa = [
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3009137", nombre: "Estadística III", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3011166", nombre: "Fundamentos de Sistemas de Información e Inteligencia de Negocios", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000006-M", nombre: "Cálculo de Varias Variables", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006935", nombre: "Procesos Estocásticos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009297", nombre: "Series de Tiempo Univariadas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007340", nombre: "Diseño de Experimentos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010394", nombre: "Teoría Básica de la Probabilidad", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000018-M", nombre: "Física Moderna", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006852", nombre: "Laboratorio de Física Moderna", creditos: 1, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009743", nombre: "Microeconomía I", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3009951", nombre: "Macroeconomía I", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010507", nombre: "Contabilidad General y de Costos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010521", nombre: "Administración Financiera", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010512", nombre: "Introducción a las Finanzas Corporativas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010518", nombre: "Matemáticas Financieras", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007324", nombre: "Investigación de Operaciones I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007325", nombre: "Investigación de Operaciones II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3011198", nombre: "Introducción a la Ingeniería Administrativa", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010425", nombre: "Teoría Administrativa y Organizacional", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010411", nombre: "Innovación y Gestión Tecnológica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010500", nombre: "Gestión del Talento Humano", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010410", nombre: "Gestión de Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010403", nombre: "Derecho para la Administración", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010396", nombre: "Administración Estratégica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010524", nombre: "Fundamentos de Mercadeo", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007323", nombre: "Investigación de Mercados", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  ];
  
  export default planIngAdministrativa;
  