export const PlanIngAmbiental = [
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000009-M", nombre: "Biología General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3007000", nombre: "Geología Física", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3007022", nombre: "Ecología General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3008596", nombre: "Microbiología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000034-M", nombre: "Química Orgánica", creditos: 3, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3009417", nombre: "Biología Evolutiva", creditos: 3, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000020-M", nombre: "Física de Oscilaciones Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010660", nombre: "Economía de Recursos Naturales y del Medio Ambiente", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3009024", nombre: "Cultura y Medio Ambiente", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010446", nombre: "Introducción a la Ingeniería Ambiental", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3006960", nombre: "Mecánica de Fluidos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010478", nombre: "Termodinámica General", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007814", nombre: "Fenómenos de Transporte", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3008999", nombre: "Fenómenos Críticos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3009001", nombre: "Planificación Integral y Ordenamiento del Territorio", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010501", nombre: "Gestión y Evaluación Ambiental", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010455", nombre: "Contaminación Ambiental", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3008231", nombre: "Derecho Ambiental", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010453", nombre: "Valoración Económica del Impacto Ambiental", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3009714", nombre: "Introducción a la Modelación Ambiental", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009002", nombre: "Análisis de Datos Ambientales", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009369", nombre: "Diseño Ambiental", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3006988", nombre: "Fundamentos de Sistemas de Información Geográfica", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007385", nombre: "Hidrología", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007383", nombre: "Hidráulica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3009004", nombre: "Biogeoquímica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3009404", nombre: "Suelos y Medio Ambiente", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007709", nombre: "Geomorfología", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010459", nombre: "Geografía Física y Humana", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010454", nombre: "Ambiente Urbano", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007382", nombre: "Hidráulica Fluvial", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009242", nombre: "Limnología", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007387", nombre: "Ingeniería de los Recursos Hidráulicos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009721", nombre: "Química Ambiental de Suelos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007050", nombre: "Manejo y Conservación de Suelos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009718", nombre: "Microbiología de Rehabilitación de Suelos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010536", nombre: "Física Atmosférica", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010444", nombre: "Gestión de la Calidad del Aire", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009006", nombre: "Climatología", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010451", nombre: "Química Atmosférica", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007465", nombre: "Oceanografía", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007389", nombre: "Ingeniería de Puertos y Costas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007466", nombre: "Geología Marina", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009392", nombre: "Campo Marino", creditos: 2, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007371", nombre: "Acueductos y Alcantarillados", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007403", nombre: "Tratamiento de Aguas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007012", nombre: "Biorremediación", creditos: 4, tipologia: "T - Disciplina Optativa" },
  { codigo: "3008998", nombre: "Residuos Sólidos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007227", nombre: "Conflictos Ambientales", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007290", nombre: "Evaluación Económica y Social de Proyectos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010452", nombre: "Sistemas de Gestión Ambiental Empresarial", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010537", nombre: "Gestión De Proyectos De Desarrollo Y Metodología General Ajustada", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010535", nombre: "Fundamentos De Ciclo De Vida Para Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" }
];