export const PlanIngCivil = [
    { codigo: "3007500", nombre: "Dibujo Asistido por Computador", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
  { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
  { codigo: "3010448", nombre: "Mecánica Básica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3006960", nombre: "Mecánica de Fluidos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010449", nombre: "Mecánica de Materiales", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010479", nombre: "Topografía", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010460", nombre: "Geología Aplicada", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010487", nombre: "Geomática Digital", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007383", nombre: "Hidráulica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007385", nombre: "Hidrología", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007371", nombre: "Acueductos y Alcantarillados", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007387", nombre: "Ingeniería de los Recursos Hidráulicos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007393", nombre: "Obras Hidráulicas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007382", nombre: "Hidráulica Fluvial", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007389", nombre: "Ingeniería de Puertos y Costas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3008597", nombre: "Hidrología Aplicada", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010450", nombre: "Mecánica Estructural", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007405", nombre: "Diseño Estructural Básico", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007407", nombre: "Diseño Estructural Avanzado", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007375", nombre: "Diseño Básico de Estructuras de Acero", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007390", nombre: "Materiales Compuestos", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007378", nombre: "Diseño Sismo Resistente", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009152", nombre: "Mampostería Estructural", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007399", nombre: "Puentes", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007386", nombre: "Hormigón Pretensionado", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009716", nombre: "Introducción al Análisis Matricial de Estructuras", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010447", nombre: "Mecánica de Suelos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010445", nombre: "Ingeniería Geotécnica", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007416", nombre: "Pavimentos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007414", nombre: "Mecánica de Rocas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007409", nombre: "Agua en el Suelo", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007410", nombre: "Estabilidad de Laderas", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3010488", nombre: "Ingeniería de Tránsito", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007408", nombre: "Diseño Geométrico de Vías", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007570", nombre: "Ferrocarriles", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007402", nombre: "Transporte Urbano", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007400", nombre: "Tópicos de Diseño de Vías", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3009126", nombre: "Técnicas de Ingeniería de Tránsito", creditos: 3, tipologia: "T - Disciplina Optativa" },
  { codigo: "3007496", nombre: "Construcción de Infraestructura Vial", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3007404", nombre: "Construcción de Edificaciones", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010659", nombre: "Programación y Presupuestos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010655", nombre: "Gerencia y Administración de Proyectos Civiles", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
  { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" }
];