export const planIngControl = [
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006935", nombre: "Procesos Estocásticos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3008953", nombre: "Física Matemática", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000009-M", nombre: "Biología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007022", nombre: "Ecología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007309", nombre: "Ciencia de los Materiales", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009530", nombre: "Introducción a la Ingeniería de Control", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010478", nombre: "Termodinámica General", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010481", nombre: "Análisis de Circuitos Eléctricos I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010496", nombre: "Análisis de Circuitos Eléctricos II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007756", nombre: "Laboratorio de Circuitos", creditos: 1, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010421", nombre: "Señales y Sistemas Lineales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010418", nombre: "Modelamiento: Electromecánica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007357", nombre: "Modelamiento: Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007354", nombre: "Identificación de Sistemas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010402", nombre: "Control: Entrada - Salida", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007344", nombre: "Control: Análisis en Variables de Estado", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010400", nombre: "Control Estructuras SISO", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010458", nombre: "Electrónica Análoga I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010457", nombre: "Electrónica Análoga II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010483", nombre: "Electrónica Digital", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010491", nombre: "Procesadores", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010494", nombre: "Telecomunicaciones", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010505", nombre: "Automatización de Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010506", nombre: "Automatización Integrada", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010412", nombre: "Instrumentación", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010424", nombre: "Taller de Instrumentación, Control y Automatización", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010498", nombre: "Automatización Avanzada", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007595", nombre: "Redes Teleinformáticas I", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007596", nombre: "Redes Teleinformáticas II", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007597", nombre: "Redes Teleinformáticas III", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010401", nombre: "Control Predictivo", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010399", nombre: "Control Adaptativo", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010509", nombre: "Control Óptimo", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010406", nombre: "Estimación de Estado", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009244", nombre: "Control de Sistemas no Lineales", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010539", nombre: "Procesamiento de señales", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010489", nombre: "Modelado de Sistemas Fotovoltaicos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010484", nombre: "Fundamentos de Electrónica de Potencia", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010493", nombre: "Sistemas en Tiempo Real", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010532", nombre: "Comunicaciones Digitales", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006876", nombre: "Taller V (Electrónica Digital y Microcontroladores)", creditos: 5, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009671", nombre: "Comunicaciones Inalámbricas y Redes de Sensores", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006844", nombre: "Fundamentos de Fibras Ópticas", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006850", nombre: "Instrumentos Ópticos", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010520", nombre: "Teoría Electromagnética", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010661", nombre: "Máquinas Eléctricas I", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010662", nombre: "Máquinas Eléctricas II", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010538", nombre: "Laboratorio de Máquinas Eléctricas", creditos: 2, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007814", nombre: "Fenómenos de Transporte", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007821", nombre: "Operaciones de Transferencia de Cantidad de Movimiento", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007811", nombre: "Balances de Materia y Energía", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007820", nombre: "Operaciones de Transferencia de Calor", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007822", nombre: "Operaciones de Transferencia de Masa", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006884", nombre: "Álgebra Lineal Aplicada", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006908", nombre: "Modelamiento Matemático", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007187", nombre: "Econometría I", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007188", nombre: "Econometría II", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3006960", nombre: "Mecánica de Fluidos", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010436", nombre: "Gestión del Mantenimiento", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007853", nombre: "Ingeniería de Software", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007744", nombre: "Programación Orientada a Objetos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007741", nombre: "Estructura de Datos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007847", nombre: "Bases de Datos I", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010426", nombre: "Teoría de Lenguajes de Programación", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010476", nombre: "Introducción a la Inteligencia Artificial", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" }
];