export const planIngElectrica = [
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3008953", nombre: "Física Matemática", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3011012", nombre: "Ecología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009531", nombre: "Introducción a la Ingeniería Eléctrica", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010478", nombre: "Termodinámica General", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010481", nombre: "Análisis de Circuitos Eléctricos I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010496", nombre: "Análisis de Circuitos Eléctricos II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007756", nombre: "Laboratorio De Circuito", creditos: 1, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010520", nombre: "Teoría Electromagnética", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010490", nombre: "Modelado De Líneas De Transmisión", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010661", nombre: "Máquinas Eléctricas I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010662", nombre: "Máquinas Eléctricas II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010538", nombre: "Laboratorio de Máquinas Eléctricas", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010658", nombre: "Instalaciones Eléctricas Industriales y Residenciales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010529", nombre: "Sistemas de Generación de Energía Eléctrica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010497", nombre: "Análisis de Sistemas de Potencia", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010492", nombre: "Sistemas de Protecciones Eléctricas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010482", nombre: "Diseño De Redes De Transmisión Y Distribución", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010458", nombre: "Electrónica Análoga I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010457", nombre: "Electrónica Análoga II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010483", nombre: "Electrónica Digital", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010494", nombre: "Telecomunicaciones", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010421", nombre: "Señales y Sistemas Lineales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010402", nombre: "Control: Entrada-Salida", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010398", nombre: "Automatización de Sistemas Eléctricos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007760", nombre: "Normatividad en Ingeniería Eléctrica", creditos: 2, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010480", nombre: "Alta Tensión", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007592", nombre: "Fenómenos Transitorios Electromagnéticos", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3008706", nombre: "Sistemas de Puesta A Tierra", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007590", nombre: "Coordinación de Aislamiento Eléctrico I", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007591", nombre: "Coordinación de Aislamiento Eléctrico II", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007765", nombre: "Subestaciones Eléctricas", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010495", nombre: "Análisis de Mercados de Energía Eléctrica", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010675", nombre: "Fundamentos de Calidad de la Potencia", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010489", nombre: "Modelado de Sistemas Fotovoltaicos", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3011061", nombre: "Tópicos de la Digitalización de la Energía", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010539", nombre: "Procesamiento de Señales", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010484", nombre: "Fundamentos de Electrónica de Potencia", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010491", nombre: "Procesadores", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010493", nombre: "Sistemas en Tiempo Real", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010532", nombre: "Comunicaciones Digitales", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006876", nombre: "Taller V (Electrónica Digital y Microcontroladores)", creditos: 5, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009671", nombre: "Comunicaciones Inalámbricas y Redes de Sensores", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006844", nombre: "Fundamentos de Fibras Ópticas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010413", nombre: "Instrumentación y Medidas", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010505", nombre: "Automatización de Procesos", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010506", nombre: "Automatización Integrada", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007595", nombre: "Redes Teleinformáticas I", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007596", nombre: "Redes Teleinformáticas II", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007597", nombre: "Redes Teleinformáticas III", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3011054", nombre: "Controles Asociados a Sistemas de Generación", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006960", nombre: "Mecánica de Fluidos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010436", nombre: "Gestión del Mantenimiento", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007853", nombre: "Ingeniería de Software", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007744", nombre: "Programación Orientada a Objetos", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007741", nombre: "Estructura de Datos", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007847", nombre: "Bases de Datos I", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "O - Fundamentación Optativa" },
];