export const planIngMecanica = [
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000009-M", nombre: "Biología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006821", nombre: "Ecología", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007796", nombre: "Introducción a la Ingeniería Mecánica", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010475", nombre: "Electrónica Básica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010418", nombre: "Modelamiento: Electromecánica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007753", nombre: "Fundamentos de Control", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010456", nombre: "Diseño Mecatrónico", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010478", nombre: "Termodinámica General", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010409", nombre: "Fundamentos de Termo-Fluidos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010427", nombre: "Transferencia de Calor", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010474", nombre: "Conversión de Energía en Sistemas Termofluídicos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010467", nombre: "Laboratorio de Ciencias Térmicas", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010441", nombre: "Dibujo Mecánico", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010434", nombre: "Estática", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010442", nombre: "Dinámica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010417", nombre: "Mecánica de Sólidos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010433", nombre: "Elementos de Máquinas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3011065", nombre: "Diseño Mecánico: Básico", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010654", nombre: "Diseño Mecánico: Conceptual", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010653", nombre: "Diseño Mecánico: Computacional", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010432", nombre: "Diseño Mecánico: Integrado", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007309", nombre: "Ciencia de Materiales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010470", nombre: "Selección de Materiales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010419", nombre: "Procesos de Manufactura I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010420", nombre: "Procesos de Manufactura II", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010416", nombre: "Laboratorio de Fabricación", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010466", nombre: "Laboratorio de Materiales", creditos: 1, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007493", nombre: "Electrotecnia", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007594", nombre: "Modelamiento: Procesos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010458", nombre: "Electrónica Análoga I", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010483", nombre: "Electrónica Digital", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010413", nombre: "Instrumentación y medidas", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010505", nombre: "Automatización de Procesos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009009", nombre: "Diseño de máquinas térmicas", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009254", nombre: "Refrigeración y Aire Acondicionado", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009355", nombre: "Laboratorio de Máquinas y Sistemas Térmicos", creditos: 2, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010468", nombre: "Máquinas y Sistemas Térmicos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007785", nombre: "CAD/CAM", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007798", nombre: "Lubricación I", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007799", nombre: "Lubricación II", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009580", nombre: "Mecanismos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009581", nombre: "Vibraciones Mecánicas", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3009579", nombre: "Fundamentos de los Ensayos no Destructivos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010436", nombre: "Gestión del Mantenimiento", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007132", nombre: "Fundición", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007793", nombre: "Fundamentos de tribología", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007805", nombre: "Procesos y Metalurgia de la Soldadura", creditos: 4, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007810", nombre: "Tratamientos Térmicos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010464", nombre: "Introducción a la Manufactura de Materiales Compuestos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3011066", nombre: "Metrología Dimensional y el Aseguramiento de las Mediciones", creditos: 2, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010656", nombre: "Gestión Integral de Activos", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010411", nombre: "Innovación y Gestión Tecnológica", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010510", nombre: "Derecho Laboral", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3007320", nombre: "Introducción a la Confiabilidad", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "T - Disciplina Optativa" }
];