export const planIngQuimica = [
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000034-M", nombre: "Química Orgánica", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3007421", nombre: "Química Analítica", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007444", nombre: "Introducción a la Química de Materiales", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006828", nombre: "Bioquímica", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000018-M", nombre: "Física Moderna", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006852", nombre: "Laboratorio de Física Moderna", creditos: 1, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006854", nombre: "Mecánica Cuántica", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006871", nombre: "Simulaciones", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006882", nombre: "Física de Radiaciones", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000009-M", nombre: "Biología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3007309", nombre: "Ciencias de los Materiales", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006802", nombre: "Biología Celular", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006817", nombre: "Biología Molecular", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009951", nombre: "Macroeconomía I", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3011012", nombre: "Ecología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009596", nombre: "Introducción a La Nanotecnología Química", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010511", nombre: "Introducción a la Ingeniería Química", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010485", nombre: "Fundamentos de Biotecnología", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3009352", nombre: "Introducción al Control de Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010478", nombre: "Termodinámica General", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010463", nombre: "Equilibrio en Sistemas Reactivos y Fenómenos de Superficie", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010530", nombre: "Termodinámica del Equilibrio de Fases para Sistemas Multicomponentes", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010514", nombre: "Laboratorio I de Ingeniería Química, Termodinámica", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007811", nombre: "Balances de Materia y Energía", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007814", nombre: "Fenómenos de Transporte", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007816", nombre: "Ingeniería de Procesos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007817", nombre: "Ingeniería de los Reactores Químicos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010515", nombre: "Laboratorio II de Ingeniería Química, Operaciones de Transferencia y Control de Procesos", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007820", nombre: "Operaciones de Transferencia de Calor", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007821", nombre: "Operaciones de Transferencia de Cantidad de Movimiento", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007822", nombre: "Operaciones de Transferencia de Masa", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007324", nombre: "Investigación de Operaciones I", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010425", nombre: "Teoría Administrativa y Organizacional", creditos: 3, tipologia: "T - Disciplina Optativa" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010430", nombre: "Tópicos Especiales en Termodinámica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010474", nombre: "Conversión de Energía en Sistemas Termofluídicos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010472", nombre: "Simulación de Procesos Químicos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010462", nombre: "Tópicos Especiales en Operaciones Unitarias", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010471", nombre: "Separación de Sistemas Multicomponentes", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010652", nombre: "Análisis de Plantas Industriales", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010477", nombre: "Laboratorio de Control de Procesos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3011183", nombre: "La Energía en el Tratamiento Sostenible de Aguas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010430", nombre: "Tópicos Especiales en Termodinámica", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010474", nombre: "Conversión de Energía en Sistemas Termoflídicos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010472", nombre: "Simulación de Procesos Químicos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010462", nombre: "Tópicos Especiales en Operaciones Unitarias", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010471", nombre: "Separación de Sistemas Multicomponentes", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010652", nombre: "Análisis de Plantas Industriales", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010477", nombre: "Laboratorio de Control de Procesos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3011183", nombre: "La Energía en el Tratamiento Sostenible de Aguas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010674", nombre: "Estrategias de Gestión y Gerencia de Proyectos en Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010537", nombre: "Gestión de Proyectos de Desarrollo y Metodología General Ajustada", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010668", nombre: "Proyectos de Innovación y Desarrollo", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010669", nombre: "Toma de Decisión para el Diseño en Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010535", nombre: "Fundamentos de Ciclo de Vida para Ingeniería", creditos: 3, tipologia: "T - Disciplinar Optativa" }
];