export const planIngSistemas = [
    { codigo: "1000004-M", nombre: "Cálculo Diferencial", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000008-M", nombre: "Geometría Vectorial y Analítica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000005-M", nombre: "Cálculo Integral", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000003-M", nombre: "Álgebra Lineal", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3006906", nombre: "Matemáticas Discretas", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "3010651", nombre: "Estadística I", creditos: 3, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000019-M", nombre: "Física Mecánica", creditos: 4, tipologia: "B - Fundamentación Obligatoria" },
    { codigo: "1000007-M", nombre: "Ecuaciones Diferenciales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000006-M", nombre: "Cálculo en Varias Variables", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006905", nombre: "Matemáticas Especiales", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006907", nombre: "Métodos Numéricos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010334", nombre: "Fundamentos de Matemáticas", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010391", nombre: "Geometría Aplicada", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006915", nombre: "Estadística II", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006927", nombre: "Estadística Descriptiva y Exploratoria", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3009137", nombre: "Estadística III", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000017-M", nombre: "Física de Electricidad y Magnetismo", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000020-M", nombre: "Física de Oscilaciones, Ondas y Óptica", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006829", nombre: "Química General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006825", nombre: "Laboratorio de Química General", creditos: 2, tipologia: "O - Fundamentación Optativa" },
    { codigo: "1000009-M", nombre: "Biología General", creditos: 3, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3006931", nombre: "Introducción al Manejo de Datos Estadísticos", creditos: 4, tipologia: "O - Fundamentación Optativa" },
    { codigo: "3010435", nombre: "Fundamentos de Programación", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007744", nombre: "Programación Orientada a Objetos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007741", nombre: "Estructura de Datos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007847", nombre: "Bases de Datos I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010426", nombre: "Teoría de Lenguajes de Programación", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010476", nombre: "Introducción a la Inteligencia Artificial", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007867", nombre: "Sistemas Operativos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007865", nombre: "Redes y Telecomunicaciones I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3011020", nombre: "Fundamentos de Analítica", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007853", nombre: "Ingeniería de Software", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007852", nombre: "Ingeniería de Requisitos", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010440", nombre: "Calidad de Software", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010438", nombre: "Introducción a la Ingeniería de Sistemas e Informática", creditos: 2, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007324", nombre: "Investigación de Operaciones I", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010415", nombre: "Introducción al Análisis de Decisiones", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3007331", nombre: "Simulación de Sistemas", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010408", nombre: "Fundamentos de Proyectos en Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010407", nombre: "Estructuración y Evaluación de Proyectos de Ingeniería", creditos: 3, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3010439", nombre: "Proyecto Integrado de Ingeniería", creditos: 4, tipologia: "C - Disciplinar Obligatoria" },
    { codigo: "3011166", nombre: "Fundamentos de Sistemas de Información e Inteligencia de Negocios", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007854", nombre: "Técnicas de Aprendizaje Estadístico", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007860", nombre: "Sistema de Recuperación de Información de web", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007862", nombre: "Visión Artificial", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3009150", nombre: "Redes Neuronales Artificiales y Algoritmos Bioinspirados", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3009151", nombre: "Introducción a la Robótica", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007850", nombre: "Diseño y Construcción de Productos de Software", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007848", nombre: "Bases de Datos II", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3009430", nombre: "Análisis y Diseño de Algoritmos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007871", nombre: "Programación Matemática", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007872", nombre: "Sistemas Complejos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007325", nombre: "Investigación de Operaciones II", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007311", nombre: "Dinámica de Sistemas", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007873", nombre: "Teoría de la Organización Industrial", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3007851", nombre: "Gestión de Proyectos de Software", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010836", nombre: "Cátedra de Sistemas: una Visión Histórico-Cultural de la Computación", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010757", nombre: "Ciencias de la Computación y Aplicaciones Móviles", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3010585", nombre: "Creación de Videojuegos", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3009936", nombre: "Seguridad Web", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3011172", nombre: "Desarrollo Web II", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3011093", nombre: "Computación Paralela", creditos: 3, tipologia: "T - Disciplinar Optativa" },
    { codigo: "3011018", nombre: "Creación Multimedia", creditos: 3, tipologia: "T - Disciplinar Optativa" }
];